### ISSUE TITLE
Mongodb 集群搭建(CentOS)

### ISSUE THREAD

**Issue by cavacn** [cavacn/Growth-notes#1]
# 安装mongodb
## 更新系统

> yum update
## 添加源

> vim /etc/yum.repos.d/mongodb-org-2.6.repo
### 粘贴复制

```
[mongodb-org-3.2]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.2/x86_64/
gpgcheck=0
enabled=1
```
## 安装mongodb

> yum install -y mongodb-org

**Comment by cavacn** [comment]
# 按照以上方式,搭建另外两台服务器

## 这样，我们就有三台服务器

> es0
> 
> es1
> 
> es2

**Comment by cavacn** [comment]
## 复制service~

```
cp /etc/init.d/mongod /etc/init.d/mongod-config
cp /etc/init.d/mongod /etc/init.d/mongod-db1
cp /etc/init.d/mongod /etc/init.d/mongod-db2
cp /etc/init.d/mongod /etc/init.d/mongod-db3
```

## 然后修改这些文件

```
vim /etc/init.d/mongod-db*
```

> 找到`CONFIGFILE=/etc/mongod.conf`依次修改`CONFIGFILE=/etc/mongod-**.conf`

### 配置示例

#### mongod-db*.conf

```
# mongod.conf

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod-db1.log

# Where and how to store data.
storage:
  dbPath: /var/lib/mongo-db1
  directoryPerDB: true
  journal:
    enabled: true
#  engine:
#  mmapv1:
#  wiredTiger:

# how the process runs
processManagement:
  fork: true  # fork and run in background
  pidFilePath: /var/run/mongodb/mongod-db1.pid  # location of pidfile

# network interfaces
net:
  port: 10001
#  bindIp: 127.0.0.1  # Listen to local interface only, comment to listen on all interfaces.


#security:

#operationProfiling:

#replication:

#sharding:
sharding:
  clusterRole: shardsvr
replication:
  replSetName: shard1

## Enterprise-Only Options

#auditLog:
```

#### mongod-config.conf

```
# mongod.conf
# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod-config.log

# Where and how to store data.
storage:
  dbPath: /var/lib/mongo-config
  directoryPerDB: true
  journal:
    enabled: true
#  engine:
#  mmapv1:
#  wiredTiger:

# how the process runs
processManagement:
  fork: true  # fork and run in background
  pidFilePath: /var/run/mongodb/mongod-config.pid  # location of pidfile

# network interfaces
net:
  port: 20000
#  bindIp: 127.0.0.1  # Listen to local interface only, comment to listen on all interfaces.


#security:

#operationProfiling:

#replication:

#sharding:
sharding:
  clusterRole: configsvr
#replication:
#  replSetName: shard1

## Enterprise-Only Options

#auditLog:
```
